/**
 * forest.js – Konfiguration für Waldbaum-Typen, Tiefenebenen und Wald-Slots.
 */

// ── Waldbaum-Typen ────────────────────────────────────────────────────────────
export const FOREST_TREE_TYPES = [
  {
    id: 'birch',
    name: 'Birke',
    emoji: '🌿',
    description: 'Schnell wachsend. Gibt Licht weiter.',
    unlockPhase: 1,
    cost: { light: 60, water: 30, nutrients: 20 },
    passiveBonus: { light: 0.25 },         // +25% Lichtrate für Hauptbaum
    trunkColor: 0xd8d0c0,
    leafColor:  0x80d850,
    trunkHeight: 70,
    levels: 2,
    branchSpread: 50,
    lore: 'Die Birke teilt ihr Licht. Sie fragt nie warum.',
  },
  {
    id: 'oak',
    name: 'Junge Eiche',
    emoji: '🌳',
    description: 'Langsam, aber stark. Nährstoffe und Symbiose.',
    unlockPhase: 2,
    cost: { light: 120, water: 60, nutrients: 80 },
    passiveBonus: { nutrients: 0.3, symbiosis: 0.2 },
    trunkColor: 0x5a3018,
    leafColor:  0x2a7020,
    trunkHeight: 90,
    levels: 3,
    branchSpread: 70,
    lore: 'Die Eiche erinnert sich an Regen, den kein Mensch gesehen hat.',
  },
  {
    id: 'fir',
    name: 'Tanne',
    emoji: '🌲',
    description: 'Immergrün. Schützt im Winter. Wasser-Speicher.',
    unlockPhase: 1,
    cost: { light: 50, water: 80, nutrients: 30 },
    passiveBonus: { water: 0.3, winterMalusReduction: 0.1 },
    trunkColor: 0x3a2010,
    leafColor:  0x1a5820,
    trunkHeight: 100,
    levels: 2,
    branchSpread: 30,
    lore: 'Die Tanne weicht dem Schnee – und überlebt ihn.',
  },
  {
    id: 'fern',
    name: 'Riesenfarn',
    emoji: '🌿',
    description: 'Bodennah. Extrem nützlich für Pilznetzwerke.',
    unlockPhase: 0,
    cost: { light: 20, water: 40, nutrients: 15 },
    passiveBonus: { nutrients: 0.15, symbiosis: 0.25 },
    trunkColor: 0x2a4010,
    leafColor:  0x50a030,
    trunkHeight: 30,
    levels: 1,
    branchSpread: 60,
    lore: 'Der Farn war schon da, als die Dinosaurier noch schliefen.',
  },
  {
    id: 'willow',
    name: 'Trauerweide',
    emoji: '🌊',
    description: 'Liebt Wasser. Zieht Regen an. Wasser +50%.',
    unlockPhase: 2,
    cost: { light: 80, water: 150, nutrients: 40 },
    passiveBonus: { water: 0.5 },
    trunkColor: 0x4a3820,
    leafColor:  0x70c850,
    trunkHeight: 85,
    levels: 2,
    branchSpread: 90,
    lore: 'Die Weide weint nicht – sie trinkt.',
  },
  {
    id: 'elder_tree',
    name: 'Holunder',
    emoji: '🍇',
    description: 'Magische Symbiose. Lockt Tiere und Pilze.',
    unlockPhase: 3,
    cost: { light: 200, water: 100, nutrients: 150 },
    passiveBonus: { symbiosis: 0.5, nutrients: 0.2 },
    trunkColor: 0x3a1a08,
    leafColor:  0x205018,
    trunkHeight: 60,
    levels: 2,
    branchSpread: 80,
    lore: 'Wer unter dem Holunder schläft, träumt von Wurzeln.',
  },
];

// ── Wald-Slots (freigeschaltet pro Hauptbaum-Phase) ───────────────────────────
// Wie viele Waldbäume darf man gleichzeitig haben?
export const FOREST_SLOTS_PER_PHASE = [1, 2, 3, 4, 6];

// ── Wurzel-Tiefenebenen ───────────────────────────────────────────────────────
export const ROOT_DEPTH_LEVELS = [
  {
    id: 'humus',
    name: 'Humusschicht',
    emoji: '🌱',
    depth: 1,
    unlockPhase: 0,
    unlockCost: null,               // Startet freigeschaltet
    description: 'Die oberste Schicht. Pilze und Insekten leben hier.',
    passiveBonus: { nutrients: 0.1 },
    visual: { color: 0x5a3a10, lineStyle: 'dashed', depth: 0.15 },
    lore: 'Der Humus ist das Gedächtnis des Waldes.',
  },
  {
    id: 'clay',
    name: 'Tonschicht',
    emoji: '🪨',
    depth: 2,
    unlockPhase: 1,
    unlockCost: { light: 100, water: 80, nutrients: 120 },
    description: 'Dichte Tonschicht. Speichert Nährstoffe über Winter.',
    passiveBonus: { nutrients: 0.25, winterMalusReduction: 0.15 },
    visual: { color: 0x8a6040, lineStyle: 'solid', depth: 0.35 },
    lore: 'Im Ton schlafen Samen, die auf das richtige Jahrhundert warten.',
  },
  {
    id: 'stone',
    name: 'Steinwurzeln',
    emoji: '⛏️',
    depth: 3,
    unlockPhase: 2,
    unlockCost: { light: 200, water: 150, nutrients: 250 },
    description: 'Wurzeln brechen Gestein. Mineralien erhöhen alle Raten.',
    passiveBonus: { nutrients: 0.4, allRatesBonus: 0.1 },
    visual: { color: 0x706050, lineStyle: 'solid', depth: 0.58 },
    lore: 'Stein ist nur sehr langsames Wasser.',
  },
  {
    id: 'groundwater',
    name: 'Grundwasser',
    emoji: '💧',
    depth: 4,
    unlockPhase: 3,
    unlockCost: { light: 350, water: 300, nutrients: 400 },
    description: 'Grundwasserader erreicht! Wasser nie wieder knapp.',
    passiveBonus: { water: 0.8, waterFloor: 20 },
    visual: { color: 0x3070a0, lineStyle: 'glow', depth: 0.78 },
    lore: 'Das Grundwasser hat keine Zeit. Es ist einfach da.',
    special: 'waterFloor',
  },
  {
    id: 'fossil',
    name: 'Fossilschicht',
    emoji: '🦕',
    depth: 5,
    unlockPhase: 3,
    unlockCost: { light: 500, water: 400, nutrients: 600 },
    description: 'Uralte Fossilien freisetzen. Nährstoff-Schub. Codex-Entdeckungen.',
    passiveBonus: { nutrients: 0.7, symbiosisBonus: 0.2 },
    visual: { color: 0xa09060, lineStyle: 'glow', depth: 0.88 },
    lore: 'Jedes Fossil war einmal ein Atemzug.',
    special: 'codexUnlock',
  },
  {
    id: 'earthcore',
    name: 'Erdadern',
    emoji: '🌍',
    depth: 6,
    unlockPhase: 4,
    unlockCost: { light: 800, water: 700, nutrients: 900 },
    description: 'Der Baum erreicht die Erdadern. Symbiose explodiert. Unsterblichkeit beginnt.',
    passiveBonus: { allRatesBonus: 0.5, symbiosis: 1.0, immortalStart: true },
    visual: { color: 0xff6020, lineStyle: 'pulse', depth: 0.97 },
    lore: 'An diesem Punkt hört der Baum auf, ein Baum zu sein.',
    special: 'immortalPath',
  },
];
