// Jahreszeiten-Konfiguration
export const SEASON_DURATION_MS = 60_000;

export const SEASONS = [
  {
    id: 'spring', name: 'Frühling', emoji: '🌸',
    skyTop: '#1a2e1a', skyBottom: '#2d5a27', groundColor: '#3d6b2a', ambientLight: '#a8d878',
    resourceMultiplier: { light: 1.2, water: 1.4, nutrients: 1.0, symbiosis: 1.3 },
    events: [
      { id: 'bloom',    name: 'Blütenpracht', emoji: '🌸', chance: 0.004, duration: 8000,
        effect: { light: +1.5, water: -0.3, nutrients: +0.5, symbiosis: +0.8 },
        description: 'Eine Blütenpracht verstärkt die Photosynthese!', color: 0xffb8d0 },
      { id: 'rain', name: 'Frühlingsregen', emoji: '🌧️', chance: 0.005, duration: 9000,
        effect: { light: -0.4, water: +2.2, nutrients: +0.5, symbiosis: +0.3 },
        description: 'Warmer Regen nährt Wurzeln und Pilze.', color: 0x6090e0 },
    ],
    description: 'Schnelles Wachstum. Neue Arten wandern ein.',
  },
  {
    id: 'summer', name: 'Sommer', emoji: '☀️',
    skyTop: '#0a1a0a', skyBottom: '#1e4a10', groundColor: '#4a7a1e', ambientLight: '#f0e060',
    resourceMultiplier: { light: 1.5, water: 0.7, nutrients: 1.2, symbiosis: 1.6 },
    events: [
      { id: 'drought', name: 'Dürre', emoji: '🔥', chance: 0.006, duration: 10000,
        effect: { light: +0.5, water: -1.8, nutrients: -0.5, symbiosis: -0.3 },
        description: 'Extreme Hitze! Wasser verdunstet rapide.', color: 0xff6020 },
      { id: 'heatwave', name: 'Hitzewelle', emoji: '🌡️', chance: 0.003, duration: 6000,
        effect: { light: +0.3, water: -1.2, nutrients: 0, symbiosis: 0 },
        description: 'Sengend heiß – Wasser ist knapp.', color: 0xffa040 },
      { id: 'pollinator', name: 'Bestäuber-Schwarm', emoji: '🐝', chance: 0.004, duration: 7000,
        effect: { light: 0, water: 0, nutrients: +0.8, symbiosis: +1.5 },
        description: 'Bienen und Schmetterlinge erhöhen die Symbiose.', color: 0xf0d020 },
    ],
    description: 'Maximale Symbiose. Aber Brandgefahr.',
  },
  {
    id: 'autumn', name: 'Herbst', emoji: '🍂',
    skyTop: '#1a1005', skyBottom: '#3d2a10', groundColor: '#5a3a0a', ambientLight: '#e08030',
    resourceMultiplier: { light: 0.9, water: 1.1, nutrients: 1.5, symbiosis: 0.9 },
    events: [
      { id: 'windstorm', name: 'Herbststurm', emoji: '🌪️', chance: 0.005, duration: 7000,
        effect: { light: -0.8, water: +1.0, nutrients: -0.6, symbiosis: -0.5 },
        description: 'Ein Sturm fegt über das Land – Ressourcen schwinden!', color: 0xd07020 },
      { id: 'harvest', name: 'Erntesegen', emoji: '🍄', chance: 0.004, duration: 6000,
        effect: { light: 0, water: 0, nutrients: +2.5, symbiosis: +1.0 },
        description: 'Gefallene Blätter nähren den Boden.', color: 0x90c040 },
      { id: 'migration', name: 'Vogelzug', emoji: '🐦', chance: 0.003, duration: 5000,
        effect: { light: 0, water: 0, nutrients: +0.5, symbiosis: +1.2 },
        description: 'Ziehende Vögel verbreiten Samen und stärken das Netz.', color: 0xc0d0f0 },
    ],
    description: 'Ressourcen sammeln für den Winter.',
  },
  {
    id: 'winter', name: 'Winter', emoji: '❄️',
    skyTop: '#050a14', skyBottom: '#0a1a2e', groundColor: '#c8d8e8', ambientLight: '#6090c0',
    resourceMultiplier: { light: 0.5, water: 0.6, nutrients: 0.4, symbiosis: 0.3 },
    events: [
      { id: 'blizzard', name: 'Schneesturm', emoji: '❄️', chance: 0.005, duration: 12000,
        effect: { light: -1.0, water: -0.8, nutrients: -1.0, symbiosis: -0.8 },
        description: 'Ein Blizzard zieht auf! Alle Ressourcen sinken.', color: 0xa0c8f0 },
      { id: 'frost', name: 'Frost', emoji: '🧊', chance: 0.007, duration: 8000,
        effect: { light: -0.5, water: -0.5, nutrients: -0.8, symbiosis: -0.4 },
        description: 'Tiefer Frost – Nährstoffe gefrieren im Boden.', color: 0x80a8ff },
      { id: 'thaw', name: 'Tauwetter', emoji: '💧', chance: 0.003, duration: 5000,
        effect: { light: +0.3, water: +1.5, nutrients: +0.3, symbiosis: +0.2 },
        description: 'Ein kurzes Tauwetter – nutze die Chance!', color: 0x80c0f0 },
    ],
    description: 'Überlebensmodus. Falsche Mutationen töten Arten.',
  },
];

// ── Baum-Phasen (5 Stufen) ────────────────────────────────────────────────
export const TREE_PHASES = [
  { id: 'seedling', name: 'Sämling', trunkHeight: 60, trunkWidth: 8, levels: 2, branchSpread: 40,
    growthCost: null, requiredSymbioses: 0, leafColor: 0x4a9a3a,
    description: 'Ein kleines Bäumchen. Voller Potenzial.', upgradeSlots: 1 },
  { id: 'young', name: 'Junger Baum', trunkHeight: 120, trunkWidth: 14, levels: 3, branchSpread: 70,
    growthCost: { light: 80, water: 40, nutrients: 20 }, requiredSymbioses: 0, leafColor: 0x3a8a2a,
    description: 'Die Krone wird sichtbar. Erste Wurzeln greifen tief.', upgradeSlots: 2 },
  { id: 'grown', name: 'Ausgewachsener Baum', trunkHeight: 200, trunkWidth: 22, levels: 4, branchSpread: 110,
    growthCost: { light: 200, water: 100, nutrients: 80 }, requiredSymbioses: 2, leafColor: 0x2a7a1a,
    description: 'Breite Krone. Das Netzwerk beginnt.', upgradeSlots: 3 },
  { id: 'elder', name: 'Alter Baum', trunkHeight: 260, trunkWidth: 28, levels: 5, branchSpread: 140,
    growthCost: { light: 350, water: 200, nutrients: 160 }, requiredSymbioses: 3, leafColor: 0x1e6a14,
    description: 'Jahrzehnte alt. Symbionten siedeln sich an.', upgradeSlots: 4 },
  { id: 'ancient', name: 'Urbaum', trunkHeight: 330, trunkWidth: 36, levels: 6, branchSpread: 170,
    growthCost: { light: 600, water: 350, nutrients: 280 }, requiredSymbioses: 5, leafColor: 0x1a6010,
    description: 'Ein Jahrtausende alter Riese. Das Ökosystem zentriert sich um dich.', upgradeSlots: 6 },
];

// ── Waldbaum-Typen ────────────────────────────────────────────────────
export const FOREST_TREE_TYPES = [
  {
    id: 'birch', name: 'Birke', emoji: '🪸',
    unlockPhase: 1,           // ab welcher Hauptbaum-Phase pflanzbar
    plantCost: { light: 60, water: 40, nutrients: 30 },
    // Passiver Bonus pro Sekunde AN DEN HAUPTBAUM
    passiveBonus: { light: 0.3, water: 0.1, nutrients: 0.1, symbiosis: 0.1 },
    maxLevel: 3,
    levels: [
      { trunkH: 55, trunkW: 6,  leafColor: 0xd0e890, desc: 'Junge Birke. Helles Licht.' },
      { trunkH: 90, trunkW: 9,  leafColor: 0xb8d870, desc: 'Gewachsene Birke. Mehr Licht + Wasser.' },
      { trunkH: 130, trunkW: 12, leafColor: 0xa0c860, desc: 'Alte Birke. Bestäubermagnet.' },
    ],
    levelUpCost: [null, { light: 80, water: 50, nutrients: 40 }, { light: 160, water: 100, nutrients: 80 }],
    bonusPerLevel: [
      { light: 0.3, water: 0.1, nutrients: 0.1, symbiosis: 0.1 },
      { light: 0.5, water: 0.2, nutrients: 0.15, symbiosis: 0.2 },
      { light: 0.8, water: 0.3, nutrients: 0.2, symbiosis: 0.35 },
    ],
    lore: 'Die Birke ist Pionierin – sie bereitet den Boden für andere.',
  },
  {
    id: 'oak', name: 'Eiche', emoji: '🌿',
    unlockPhase: 2,
    plantCost: { light: 100, water: 80, nutrients: 70 },
    maxLevel: 3,
    levels: [
      { trunkH: 70, trunkW: 10, leafColor: 0x4a8a2a, desc: 'Junge Eiche. Solide Nährstoffe.' },
      { trunkH: 120, trunkW: 16, leafColor: 0x3a7a1a, desc: 'Starke Eiche. Pilznetz verstärkt.' },
      { trunkH: 170, trunkW: 22, leafColor: 0x2a6a10, desc: 'Ureiche. Trägt den halben Wald.' },
    ],
    levelUpCost: [null, { light: 120, water: 80, nutrients: 100 }, { light: 250, water: 160, nutrients: 200 }],
    bonusPerLevel: [
      { light: 0.1, water: 0.2, nutrients: 0.5, symbiosis: 0.2 },
      { light: 0.2, water: 0.3, nutrients: 0.8, symbiosis: 0.4 },
      { light: 0.3, water: 0.5, nutrients: 1.2, symbiosis: 0.7 },
    ],
    lore: 'Eine Eiche kann hundert Arten beherbergen.',
  },
  {
    id: 'pine', name: 'Kiefer', emoji: '🌲',
    unlockPhase: 1,
    plantCost: { light: 50, water: 30, nutrients: 50 },
    maxLevel: 3,
    levels: [
      { trunkH: 80, trunkW: 7,  leafColor: 0x2a5a18, desc: 'Junge Kiefer. Nährstoffe + Winter.' },
      { trunkH: 140, trunkW: 11, leafColor: 0x1e4a12, desc: 'Kiefer. Winterschutz für den Wald.' },
      { trunkH: 190, trunkW: 15, leafColor: 0x183a0e, desc: 'Uraltbaum. Kein Blattfall im Winter.' },
    ],
    levelUpCost: [null, { light: 70, water: 40, nutrients: 70 }, { light: 150, water: 80, nutrients: 150 }],
    bonusPerLevel: [
      { light: 0.1, water: 0.1, nutrients: 0.4, symbiosis: 0.15 },
      { light: 0.2, water: 0.15, nutrients: 0.6, symbiosis: 0.25 },
      { light: 0.3, water: 0.2, nutrients: 0.9, symbiosis: 0.4 },
    ],
    lore: 'Die Kiefer trotzt jedem Winter – ihr Harz ist Medizin und Schutz.',
  },
  {
    id: 'willow', name: 'Weide', emoji: '🌾',
    unlockPhase: 2,
    plantCost: { light: 80, water: 120, nutrients: 40 },
    maxLevel: 3,
    levels: [
      { trunkH: 65, trunkW: 8,  leafColor: 0x90c840, desc: 'Junge Weide. Wasser-Magnet.' },
      { trunkH: 110, trunkW: 13, leafColor: 0x78b030, desc: 'Weide. Grundwasser-Zugang.' },
      { trunkH: 150, trunkW: 18, leafColor: 0x60a020, desc: 'Trauerweide. Wasser-Quelle.' },
    ],
    levelUpCost: [null, { light: 100, water: 150, nutrients: 50 }, { light: 200, water: 280, nutrients: 100 }],
    bonusPerLevel: [
      { light: 0.05, water: 0.6, nutrients: 0.1, symbiosis: 0.2 },
      { light: 0.1, water: 1.0, nutrients: 0.15, symbiosis: 0.35 },
      { light: 0.15, water: 1.5, nutrients: 0.2, symbiosis: 0.5 },
    ],
    lore: 'Die Weide liebt das Wasser – ihr Wurzelnetz reicht bis zum Grundwasser.',
  },
  {
    id: 'fern_giant', name: 'Riesenfarn', emoji: '🌿',
    unlockPhase: 3,
    plantCost: { light: 120, water: 100, nutrients: 150 },
    maxLevel: 2,
    levels: [
      { trunkH: 30, trunkW: 4,  leafColor: 0x60c050, desc: 'Urwald-Farn. Symbiose +.' },
      { trunkH: 50, trunkW: 6,  leafColor: 0x40a038, desc: 'Riesenfarn. Maximale Symbiose.' },
    ],
    levelUpCost: [null, { light: 200, water: 180, nutrients: 250 }],
    bonusPerLevel: [
      { light: 0.05, water: 0.2, nutrients: 0.3, symbiosis: 0.6 },
      { light: 0.1, water: 0.4, nutrients: 0.5, symbiosis: 1.0 },
    ],
    lore: 'Der Farn ist älter als die Dinosaurier – er kennt die Sprache der Erde.',
  },
  {
    id: 'elder_tree', name: 'Holunder', emoji: '🌺',
    unlockPhase: 3,
    plantCost: { light: 140, water: 90, nutrients: 120 },
    maxLevel: 3,
    levels: [
      { trunkH: 60, trunkW: 7,  leafColor: 0x8a6a30, desc: 'Holunder. Verbindet alle Baumarten.' },
      { trunkH: 95, trunkW: 11, leafColor: 0x705820, desc: 'Holunder. Alle Boni +20%.' },
      { trunkH: 130, trunkW: 15, leafColor: 0x584810, desc: 'Urholunder. Wald-Synergie verdoppelt.' },
    ],
    levelUpCost: [null, { light: 180, water: 120, nutrients: 160 }, { light: 360, water: 240, nutrients: 320 }],
    bonusPerLevel: [
      { light: 0.2, water: 0.2, nutrients: 0.2, symbiosis: 0.4 },
      { light: 0.35, water: 0.35, nutrients: 0.35, symbiosis: 0.7 },
      { light: 0.5, water: 0.5, nutrients: 0.5, symbiosis: 1.0 },
    ],
    lore: 'Der Holunder ist der Geist des Waldes – er verbindet alle.',
  },
];

// ── Wurzeltiefe-Ebenen ────────────────────────────────────────────────
export const ROOT_DEPTH_LEVELS = [
  {
    id: 'humus', depth: 0, name: 'Humusschicht', emoji: '🌱',
    unlockPhase: 0,
    unlockCost: null,   // automatisch
    color: 0x5a3a18,
    description: 'Oberflächliche Wurzeln. Basis-Nährstoffe.',
    passiveBonus: { nutrients: 0.1 },
    lore: 'Die oberste Schicht ist lebendig – voller Bakterien und Pilzfäden.',
    discovery: null,
  },
  {
    id: 'clay', depth: 1, name: 'Tonschicht', emoji: '🪨',
    unlockPhase: 1,
    unlockCost: { light: 120, water: 80, nutrients: 100 },
    color: 0x8a6040,
    description: 'Ton speichert Wasser. Wasser +25% permanent.',
    passiveBonus: { water: 0.25, nutrients: 0.05 },
    lore: 'Tonminerale halten Wasser und Nährstoffe wie ein Schwamm.',
    discovery: 'clay_minerals',
  },
  {
    id: 'rock', depth: 2, name: 'Steinschicht', emoji: '🪨',
    unlockPhase: 2,
    unlockCost: { light: 200, water: 150, nutrients: 200 },
    color: 0x706050,
    description: 'Wurzeln sprengen Gestein. Nährstoffe aus Mineralien.',
    passiveBonus: { nutrients: 0.4, symbiosis: 0.1 },
    lore: 'Wurzeln wachsen in Felsspalten – sie schaffen Erde aus Stein.',
    discovery: 'stone_crystals',
  },
  {
    id: 'groundwater', depth: 3, name: 'Grundwasser', emoji: '💧',
    unlockPhase: 3,
    unlockCost: { light: 300, water: 250, nutrients: 350 },
    color: 0x3060a0,
    description: 'Grundwasser angezapft. Wasser +80% konstant. Trockenheit kein Thema mehr.',
    passiveBonus: { water: 0.8 },
    waterFloor: 20,    // Wasser fällt nie unter diesen Wert
    lore: 'Unter dem Boden liegen Meere – die Wurzeln des Urbaums haben sie gefunden.',
    discovery: 'fossil_water',
  },
  {
    id: 'fossil_layer', depth: 4, name: 'Fossilienschicht', emoji: '🦴',
    unlockPhase: 3,
    unlockCost: { light: 400, water: 300, nutrients: 500 },
    color: 0x907050,
    description: 'Uralte organische Reste. Nährstoffe +60% + neue Codex-Entdeckungen.',
    passiveBonus: { nutrients: 0.6, symbiosis: 0.2 },
    lore: 'Die Fossilien erzählen von Wäldern, die längst verschwunden sind.',
    discovery: 'ancient_fossil',
  },
  {
    id: 'earth_veins', depth: 5, name: 'Erdadern', emoji: '🌍',
    unlockPhase: 4,
    unlockCost: { light: 600, water: 500, nutrients: 700 },
    color: 0x402080,
    description: 'Geothermal-Energie. Alle Raten +30%. Nur der Urbaum kann sie erreichen.',
    passiveBonus: { light: 0.3, water: 0.3, nutrients: 0.3, symbiosis: 0.5 },
    allRatesBonus: 0.3,
    lore: 'Tief im Erdinnern pulst eine Energie, die älter ist als das Leben selbst.',
    discovery: 'earth_core',
  },
];

// ── Ressourcen ────────────────────────────────────────────────────────────
export const RESOURCES = {
  light:     { name: 'Licht',      emoji: '☀️', color: '#f0e060', max: 500, baseRate: 0.8 },
  water:     { name: 'Wasser',     emoji: '💧', color: '#60a0f0', max: 500, baseRate: 0.5 },
  nutrients: { name: 'Nährstoffe', emoji: '🌱', color: '#80c040', max: 500, baseRate: 0.3 },
  symbiosis: { name: 'Symbiose',   emoji: '🪸', color: '#40d0a0', max: 500, baseRate: 0.15 },
};

// ── Mutationen (14 total, mit Upgrade-Stufen) ─────────────────────────────
export const MUTATIONS = [
  { id: 'deep_roots', name: 'Tiefe Wurzeln', emoji: '🌿', type: 'passive', requiredPhase: 0, exclusiveWith: [],
    lore: 'Unter der Erde träumt der Baum von Meeren, die längst verschwunden sind.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Tiefere Wurzeln. Wasser +40%.', cost: { light: 60, water: 20, nutrients: 30 }, effect: { waterRateBonus: 0.4 }, visual: { rootExtra: 2 } },
      { level: 2, description: 'Wurzeln erreichen Grundwasser. Wasser +70%. Dürre-Schutz -20%.', cost: { light: 100, water: 40, nutrients: 60 }, effect: { waterRateBonus: 0.7, droughtReduction: 0.2 }, visual: { rootExtra: 4 } },
      { level: 3, description: 'Uralte Wasseradern angezapft. Wasser +120%. Kein Verdursten.', cost: { light: 200, water: 80, nutrients: 120 }, effect: { waterRateBonus: 1.2, waterFloor: 5 }, visual: { rootExtra: 7, rootGlow: true } },
    ] },
  { id: 'thick_bark', name: 'Dicke Rinde', emoji: '🪵', type: 'passive', requiredPhase: 1, exclusiveWith: ['bioluminescence'],
    lore: 'Jahresringe erzählen von Stürmen, die der Baum überstand.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Dickere Rinde. Alle Verluste durch Events -15%.', cost: { light: 50, water: 30, nutrients: 50 }, effect: { eventDamageReduction: 0.15 }, visual: {} },
      { level: 2, description: 'Gehärtete Rinde. Event-Verluste -30%.', cost: { light: 120, water: 60, nutrients: 100 }, effect: { eventDamageReduction: 0.30 }, visual: { trunkScar: true } },
      { level: 3, description: 'Steinrinde. Event-Verluste -50%. Immun gegen Frost.', cost: { light: 250, water: 120, nutrients: 200 }, effect: { eventDamageReduction: 0.50, frostImmune: true }, visual: { trunkScar: true, trunkColorTint: 0x605040 } },
    ] },
  { id: 'photosynthesis_plus', name: 'Sonnenblätter', emoji: '☀️', type: 'passive', requiredPhase: 0, exclusiveWith: [],
    lore: 'Manche Blätter sind so groß, dass Vögel darunter schlafen.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Breitere Blätter. Licht +30%.', cost: { light: 40, water: 20, nutrients: 15 }, effect: { lightRateBonus: 0.3 }, visual: {} },
      { level: 2, description: 'Riesige Blätter. Licht +60%.', cost: { light: 100, water: 40, nutrients: 50 }, effect: { lightRateBonus: 0.6 }, visual: { leafSizeBonus: 0.3 } },
      { level: 3, description: 'Photosynthetische Perfektion. Licht +100%. Licht nie unter 10.', cost: { light: 220, water: 80, nutrients: 100 }, effect: { lightRateBonus: 1.0, lightFloor: 10 }, visual: { leafSizeBonus: 0.6, leafGlow: true, leafColor: 0xf8f040 } },
    ] },
  { id: 'bioluminescence', name: 'Biolumineszenz', emoji: '✨', type: 'active', requiredPhase: 1, exclusiveWith: ['fire_bark', 'thick_bark'],
    lore: 'In der Nacht leuchtet der Wald wie ein lebendiger Sternenhimmel.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Blätter leuchten. Nährstoffe +50%, Wasser -20%.', cost: { light: 120, water: 50, nutrients: 40 }, effect: { nutrientsRateBonus: 0.5, waterRateBonus: -0.2 }, visual: { leafGlow: true, leafColor: 0x40ff80 } },
      { level: 2, description: 'Pulsierendes Leuchten. Nährstoffe +90%.', cost: { light: 220, water: 60, nutrients: 80 }, effect: { nutrientsRateBonus: 0.9, waterRateBonus: -0.15 }, visual: { leafGlow: true, leafColor: 0x20ff60, glowRadius: 1.8 } },
      { level: 3, description: 'Geisterlicht. Nährstoffe +150%.', cost: { light: 400, water: 80, nutrients: 160 }, effect: { nutrientsRateBonus: 1.5, waterRateBonus: -0.1, symbiosisBonus: 0.6 }, visual: { leafGlow: true, leafColor: 0x00ffaa, glowRadius: 2.5 } },
    ] },
  { id: 'sun_crown', name: 'Sonnen-Krone', emoji: '🌞', type: 'active', requiredPhase: 1, exclusiveWith: [],
    lore: 'Manche Bäume verbiegen ihr ganzes Leben, um dem Licht zu folgen.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Krone zur Sonne. Licht +60%.', cost: { light: 150, water: 30, nutrients: 60 }, effect: { lightRateBonus: 0.6 }, visual: { leafColor: 0xf0d020, crownTilt: true } },
      { level: 2, description: 'Goldene Krone. Licht +110%.', cost: { light: 280, water: 50, nutrients: 120 }, effect: { lightRateBonus: 1.1 }, visual: { leafColor: 0xffc000, crownTilt: true, leafSizeBonus: 0.2 } },
      { level: 3, description: 'Sonnengott-Krone. Licht +180%.', cost: { light: 500, water: 80, nutrients: 220 }, effect: { lightRateBonus: 1.8, allRatesBonus: 0.1 }, visual: { leafColor: 0xffe000, crownTilt: true, leafSizeBonus: 0.5, leafGlow: true } },
    ] },
  { id: 'rain_call', name: 'Regenruf', emoji: '🌧️', type: 'active', requiredPhase: 2, exclusiveWith: [],
    lore: 'Die Transpiration des Baumes verändert das lokale Klima.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Baum zieht leichten Regen an. Wasser +35%.', cost: { light: 100, water: 80, nutrients: 60 }, effect: { waterRateBonus: 0.35 }, visual: {} },
      { level: 2, description: 'Regenwolken entstehen. Wasser +70%.', cost: { light: 200, water: 150, nutrients: 120 }, effect: { waterRateBonus: 0.7 }, visual: { cloudParticles: true } },
      { level: 3, description: 'Meister des Wetters. Wasser +120%. Dürren seltener.', cost: { light: 380, water: 280, nutrients: 220 }, effect: { waterRateBonus: 1.2, eventSuppression: { drought: 0.5, heatwave: 0.5 } }, visual: { cloudParticles: true } },
    ] },
  { id: 'mycel_bridge', name: 'Myzelbrücke', emoji: '🍄', type: 'symbiosis', requiredPhase: 1, exclusiveWith: [],
    lore: 'Unter jedem Wald schlägt ein zweites Herz aus Pilzfäden.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Pilznetzwerk. Alle Raten +20%.', cost: { light: 80, water: 80, nutrients: 100 }, effect: { allRatesBonus: 0.2 }, visual: { showMycel: true } },
      { level: 2, description: 'Dichtes Netz. Alle Raten +40%.', cost: { light: 160, water: 150, nutrients: 200 }, effect: { allRatesBonus: 0.4 }, visual: { showMycel: true, mycelDensity: 2 } },
      { level: 3, description: 'Weltennetz. Alle Raten +70%.', cost: { light: 320, water: 280, nutrients: 380 }, effect: { allRatesBonus: 0.7 }, visual: { showMycel: true, mycelDensity: 3, mycelGlow: true } },
    ] },
  { id: 'root_network', name: 'Wurzelnetz', emoji: '🌐', type: 'symbiosis', requiredPhase: 2, exclusiveWith: [],
    lore: 'Ein Wald ist kein Wettbewerb – er ist ein Gespräch.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Wurzeln teilen Wasser. +25%.', cost: { light: 60, water: 120, nutrients: 80 }, effect: { allRatesBonus: 0.1, waterRateBonus: 0.25 }, visual: { rootExtra: 3 } },
      { level: 2, description: 'Weitverzweigtes Netz. Alle +20%.', cost: { light: 140, water: 220, nutrients: 160 }, effect: { allRatesBonus: 0.2, waterRateBonus: 0.4 }, visual: { rootExtra: 5 } },
      { level: 3, description: 'Lebendiges Erdnetz. Alle +35%.', cost: { light: 300, water: 400, nutrients: 300 }, effect: { allRatesBonus: 0.35, waterRateBonus: 0.6, resourceFloor: 1 }, visual: { rootExtra: 8, rootGlow: true } },
    ] },
  { id: 'lichen_coat', name: 'Flechtenkranz', emoji: '🧫', type: 'symbiosis', requiredPhase: 2, exclusiveWith: [],
    lore: 'Flechten sind die ältesten Lebensformen — sie kennen Geduld.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Flechten. Nährstoffe +30%.', cost: { light: 70, water: 60, nutrients: 90 }, effect: { nutrientsRateBonus: 0.3, waterRateBonus: 0.15 }, visual: { lichens: true } },
      { level: 2, description: 'Dicker Flechtenteppich. Nährstoffe +60%.', cost: { light: 160, water: 120, nutrients: 180 }, effect: { nutrientsRateBonus: 0.6, symbiosisBonus: 0.25 }, visual: { lichens: true, lichenDense: true } },
      { level: 3, description: 'Uralte Flechten. Nährstoffe +100%. Wintermalus halbiert.', cost: { light: 320, water: 240, nutrients: 360 }, effect: { nutrientsRateBonus: 1.0, winterMalusReduction: 0.5 }, visual: { lichens: true, lichenDense: true, lichenGlow: true } },
    ] },
  { id: 'fire_bark', name: 'Feuerfeste Rinde', emoji: '🔥', type: 'crisis', requiredPhase: 1, requiredCrisis: 'drought', exclusiveWith: ['bioluminescence'],
    lore: 'Was das Feuer nicht bricht, macht es unsterblich.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Dürre-Wasserverlust -30%.', cost: { light: 0, water: 0, nutrients: 0 }, effect: { waterDrainReduction: 0.3 }, visual: { trunkColorTint: 0x8a2010 } },
      { level: 2, description: 'Ascheschicht. Verlust -55%.', cost: { light: 80, water: 0, nutrients: 40 }, effect: { waterDrainReduction: 0.55 }, visual: { trunkColorTint: 0x6a1808 } },
      { level: 3, description: 'Phönix-Rinde. Verlust -80%. Dürren geben Licht.', cost: { light: 200, water: 0, nutrients: 100 }, effect: { waterDrainReduction: 0.8 }, visual: { trunkColorTint: 0x501006, trunkGlow: 0xff4010 } },
    ] },
  { id: 'storm_roots', name: 'Sturmwurzeln', emoji: '🌪️', type: 'crisis', requiredPhase: 2, requiredCrisis: 'windstorm', exclusiveWith: [],
    lore: 'Der Sturm biegt – aber der Baum bricht nicht.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Sturm-Verluste -40%.', cost: { light: 0, water: 0, nutrients: 0 }, effect: { stormDamageReduction: 0.4 }, visual: { rootExtra: 3 } },
      { level: 2, description: 'Sturm-Verluste -60%.', cost: { light: 100, water: 50, nutrients: 60 }, effect: { stormDamageReduction: 0.6 }, visual: { rootExtra: 5 } },
      { level: 3, description: 'Immun gegen Wind.', cost: { light: 250, water: 100, nutrients: 150 }, effect: { stormDamageReduction: 1.0 }, visual: { rootExtra: 7, rootGlow: true } },
    ] },
  { id: 'frost_heart', name: 'Frostherz', emoji: '🧊', type: 'crisis', requiredPhase: 1, requiredCrisis: 'frost', exclusiveWith: [],
    lore: 'Im Kern des Eises schlägt ein warmes Herz.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Winter-Mali -25%.', cost: { light: 0, water: 0, nutrients: 0 }, effect: { winterMalusReduction: 0.25 }, visual: {} },
      { level: 2, description: 'Winter-Mali -50%.', cost: { light: 60, water: 40, nutrients: 80 }, effect: { winterMalusReduction: 0.5 }, visual: { leafColor: 0xc0e8ff } },
      { level: 3, description: 'Immun gegen Frost. Winter wie Herbst.', cost: { light: 160, water: 100, nutrients: 200 }, effect: { frostImmune: true, winterAsAutumn: true }, visual: { leafColor: 0xa0d0ff, leafGlow: true } },
    ] },
  { id: 'ancient_wisdom', name: 'Uraltes Wissen', emoji: '🌍', type: 'passive', requiredPhase: 3, exclusiveWith: [],
    lore: 'Der Baum erinnert sich an Kontinente, die es nicht mehr gibt.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Alle Raten +25%.', cost: { light: 300, water: 200, nutrients: 200 }, effect: { allRatesBonus: 0.25 }, visual: {} },
      { level: 2, description: 'Alle Raten +50%.', cost: { light: 600, water: 400, nutrients: 400 }, effect: { allRatesBonus: 0.5 }, visual: { symbionts: ['owl', 'moss'] } },
      { level: 3, description: 'Alle Raten +80%.', cost: { light: 1200, water: 800, nutrients: 800 }, effect: { allRatesBonus: 0.8 }, visual: { symbionts: ['owl', 'moss', 'deer'] } },
    ] },
  { id: 'world_root', name: 'Weltenwurzel', emoji: '🌏', type: 'symbiosis', requiredPhase: 4, exclusiveWith: [],
    lore: 'Wenn der Urbaum atmet, bewegt sich die Welt.',
    unlocked: false, active: false, level: 0,
    upgrades: [
      { level: 1, description: 'Symbiose +100%.', cost: { light: 500, water: 500, nutrients: 500 }, effect: { symbiosisBonus: 1.0, allRatesBonus: 0.3 }, visual: { rootExtra: 10, rootGlow: true } },
      { level: 2, description: 'Ressourcen regenerieren auch bei 0.', cost: { light: 1000, water: 1000, nutrients: 1000 }, effect: { symbiosisBonus: 1.5, allRatesBonus: 0.5, resourceFloor: 5 }, visual: { rootExtra: 14, rootGlow: true, mycelGlow: true } },
      { level: 3, description: '🌍 ENDZIEL: Unsterblich.', cost: { light: 2000, water: 2000, nutrients: 2000 }, effect: { immortal: true, allRatesBonus: 1.0 }, visual: { rootExtra: 20, rootGlow: true, mycelGlow: true, leafGlow: true } },
    ] },
];

export const SYMBIONTS = [
  { id: 'moss',     name: 'Moos',         emoji: '🌿', unlockCondition: 'lichen_coat_1',    visual: 'moss' },
  { id: 'mushroom', name: 'Pilz',         emoji: '🍄', unlockCondition: 'mycel_bridge_1',   visual: 'mushroom' },
  { id: 'owl',      name: 'Eule',         emoji: '🦉', unlockCondition: 'ancient_wisdom_2', visual: 'owl' },
  { id: 'deer',     name: 'Hirsch',       emoji: '🦌', unlockCondition: 'ancient_wisdom_3', visual: 'deer' },
  { id: 'firefly',  name: 'Glühwürmchen', emoji: '🪲', unlockCondition: 'bioluminescence_2', visual: 'firefly' },
  { id: 'bee',      name: 'Biene',        emoji: '🐝', unlockCondition: 'sun_crown_2',      visual: 'bee' },
];

export const CODEX_ENTRIES = [
  { id: 'myzel',        name: 'Myzel',             icon: '🍄', cat: 'Pilznetzwerke', cond: 'Bodenfeuchte ≥ 70%',           unlocked: false },
  { id: 'glowshroom',   name: 'Geisterpilz',        icon: '🟟', cat: 'Pilznetzwerke', cond: 'Biolumineszenz aktiv',         unlocked: false },
  { id: 'fireswamp',    name: 'Feuerschwamm',       icon: '🔴', cat: 'Pilznetzwerke', cond: 'Dürre-Event überleben',        unlocked: false },
  { id: 'firefly',      name: 'Glühwürmchen',       icon: '🪲', cat: 'Tiere',         cond: 'Biolumineszenz + Sommer',      unlocked: false },
  { id: 'boar',         name: 'Wildschwein',        icon: '🐗', cat: 'Tiere',         cond: '5+ Jahre, Nährstoffe > 300',   unlocked: false },
  { id: 'moth',         name: 'Riesenmotte',        icon: '🦋', cat: 'Tiere',         cond: 'Myzelbrücke + Nacht',          unlocked: false },
  { id: 'owl',          name: 'Eule',               icon: '🦉', cat: 'Tiere',         cond: 'Alter Baum + Winter',          unlocked: false },
  { id: 'deer',         name: 'Hirsch',             icon: '🦌', cat: 'Tiere',         cond: 'Urbaum erreicht',              unlocked: false },
  { id: 'bee',          name: 'Biene',              icon: '🐝', cat: 'Tiere',         cond: 'Bestäuber-Schwarm + Sommer',   unlocked: false },
  { id: 'sundew',       name: 'Sonnentau',          icon: '🌿', cat: 'Pflanzen',      cond: 'Frühling + Wasser > 350',      unlocked: false },
  { id: 'titan_arum',   name: 'Titanenwurz',        icon: '🌺', cat: 'Pflanzen',      cond: 'Jahr 10+, Symbiose > 300',     unlocked: false },
  { id: 'moonflower',   name: 'Mondblume',          icon: '🌙', cat: 'Pflanzen',      cond: 'Winter überleben + Biolum',    unlocked: false },
  { id: 'lichen',       name: 'Uralte Flechte',     icon: '🧫', cat: 'Pflanzen',      cond: 'Flechtenkranz Stufe 3',        unlocked: false },
  { id: 'parasite',     name: 'Schmarotzerpflanze', icon: '🦠', cat: 'Parasiten',     cond: 'Krisen-Event überleben',        unlocked: false },
  // Wald & Tiefe
  { id: 'clay_minerals',  name: 'Tonminerale',      icon: '🪨', cat: 'Tiefenschicht',  cond: 'Tonschicht erschlossen',       unlocked: false },
  { id: 'stone_crystals', name: 'Steinkristalle',   icon: '💠', cat: 'Tiefenschicht',  cond: 'Steinschicht erschlossen',     unlocked: false },
  { id: 'fossil_water',   name: 'Fossilwasser',     icon: '💧', cat: 'Tiefenschicht',  cond: 'Grundwasser angezapft',        unlocked: false },
  { id: 'ancient_fossil', name: 'Urzeitfossil',     icon: '🦴', cat: 'Tiefenschicht',  cond: 'Fossilienschicht gefunden',    unlocked: false },
  { id: 'earth_core',     name: 'Erdkern-Ader',     icon: '🌍', cat: 'Tiefenschicht',  cond: 'Erdadern erschlossen',         unlocked: false },
  { id: 'forest_birch',   name: 'Birkenwald',       icon: '🪸', cat: 'Wald',           cond: '3 Birken gepflanzt',           unlocked: false },
  { id: 'forest_oak',     name: 'Eichenhain',       icon: '🌿', cat: 'Wald',           cond: 'Eiche auf max. Stufe',         unlocked: false },
  { id: 'full_forest',    name: 'Vollständiger Wald', icon: '🌳', cat: 'Wald',         cond: '5 verschiedene Baumarten',     unlocked: false },
  { id: 'eternal',        name: 'Ewiger Schwamm',   icon: '♾️', cat: 'Legendarys',    cond: 'Alle Pilze entdeckt',           unlocked: false },
  { id: 'worldroot',      name: 'Weltenwurzel',     icon: '🌍', cat: 'Legendarys',    cond: 'Weltenwurzel Stufe 3',          unlocked: false },
];
