// Jahreszeiten-Konfiguration
// Alle Werte zentral änderbar – kein Magic-Number-Problem

export const SEASON_DURATION_MS = 60_000; // 60 Sekunden pro Jahreszeit (anpassbar)

export const SEASONS = [
  {
    id: 'spring',
    name: 'Frühling',
    emoji: '🌸',
    skyTop: '#1a2e1a',
    skyBottom: '#2d5a27',
    groundColor: '#3d6b2a',
    ambientLight: '#a8d878',
    // Ressourcen-Raten-Multiplikatoren
    resourceMultiplier: { light: 1.2, water: 1.4, nutrients: 1.0 },
    // Saisonale Ereignisse: name, Wahrscheinlichkeit pro Tick, Effekte
    events: [
      {
        id: 'bloom',
        name: 'Blütenpracht',
        emoji: '🌸',
        chance: 0.004, // ~0.4% pro Sekunde
        duration: 8000,
        effect: { light: +1.5, water: -0.3, nutrients: +0.5 },
        description: 'Eine Blütenpracht verstärkt die Photosynthese!',
        color: 0xffb8d0,
      },
    ],
    description: 'Schnelles Wachstum. Neue Arten wandern ein.',
  },
  {
    id: 'summer',
    name: 'Sommer',
    emoji: '☀️',
    skyTop: '#0a1a0a',
    skyBottom: '#1e4a10',
    groundColor: '#4a7a1e',
    ambientLight: '#f0e060',
    resourceMultiplier: { light: 1.5, water: 0.7, nutrients: 1.2 },
    events: [
      {
        id: 'drought',
        name: 'Dürre',
        emoji: '🔥',
        chance: 0.006,
        duration: 10000,
        effect: { light: +0.5, water: -1.8, nutrients: -0.5 },
        description: 'Extreme Hitze! Wasser verdunstet rapide.',
        color: 0xff6020,
      },
      {
        id: 'heatwave',
        name: 'Hitzewelle',
        emoji: '🌡️',
        chance: 0.003,
        duration: 6000,
        effect: { light: +0.3, water: -1.2, nutrients: 0 },
        description: 'Sengend heiß – Wasser ist knapp.',
        color: 0xffa040,
      },
    ],
    description: 'Maximale Symbiose. Aber Brandgefahr.',
  },
  {
    id: 'autumn',
    name: 'Herbst',
    emoji: '🍂',
    skyTop: '#1a1005',
    skyBottom: '#3d2a10',
    groundColor: '#5a3a0a',
    ambientLight: '#e08030',
    resourceMultiplier: { light: 0.9, water: 1.1, nutrients: 1.5 },
    events: [
      {
        id: 'windstorm',
        name: 'Herbststurm',
        emoji: '🌪️',
        chance: 0.005,
        duration: 7000,
        effect: { light: -0.8, water: +1.0, nutrients: -0.6 },
        description: 'Ein Sturm fegt über das Land – Ressourcen schwinden!',
        color: 0xd07020,
      },
      {
        id: 'harvest',
        name: 'Erntesegen',
        emoji: '🍄',
        chance: 0.004,
        duration: 6000,
        effect: { light: 0, water: 0, nutrients: +2.5 },
        description: 'Gefallene Blätter nähren den Boden.',
        color: 0x90c040,
      },
    ],
    description: 'Ressourcen sammeln für den Winter.',
  },
  {
    id: 'winter',
    name: 'Winter',
    emoji: '❄️',
    skyTop: '#050a14',
    skyBottom: '#0a1a2e',
    groundColor: '#c8d8e8',
    ambientLight: '#6090c0',
    resourceMultiplier: { light: 0.5, water: 0.6, nutrients: 0.4 },
    events: [
      {
        id: 'blizzard',
        name: 'Schneesturm',
        emoji: '❄️',
        chance: 0.005,
        duration: 12000,
        effect: { light: -1.0, water: -0.8, nutrients: -1.0 },
        description: 'Ein Blizzard zieht auf! Alle Ressourcen sinken schnell.',
        color: 0xa0c8f0,
      },
      {
        id: 'frost',
        name: 'Frost',
        emoji: '🧊',
        chance: 0.007,
        duration: 8000,
        effect: { light: -0.5, water: -0.5, nutrients: -0.8 },
        description: 'Tiefer Frost – Nährstoffe gefrieren im Boden.',
        color: 0x80a8ff,
      },
    ],
    description: 'Überlebensmodus. Falsche Mutationen töten Arten.',
  },
];

export const TREE_PHASES = [
  {
    id: 'seedling',
    name: 'Sämling',
    trunkHeight: 60,
    trunkWidth: 8,
    levels: 2,
    branchSpread: 40,
    // Wachstumsbedingungen (werden aus Ressourcen bezahlt)
    growthCost: null, // Startphase
    requiredSymbioses: 0,
    leafColor: 0x4a9a3a,
    description: 'Ein kleines Bäumchen. Voller Potenzial.',
  },
  {
    id: 'young',
    name: 'Junger Baum',
    trunkHeight: 120,
    trunkWidth: 14,
    levels: 3,
    branchSpread: 70,
    // Kosten für Wachstum in diese Phase
    growthCost: { light: 80, water: 40, nutrients: 20 },
    requiredSymbioses: 0,
    leafColor: 0x3a8a2a,
    description: 'Die Krone wird sichtbar. Erste Wurzeln greifen tief.',
  },
  {
    id: 'grown',
    name: 'Ausgewachsener Baum',
    trunkHeight: 200,
    trunkWidth: 22,
    levels: 4,
    branchSpread: 110,
    growthCost: { light: 200, water: 100, nutrients: 80 },
    requiredSymbioses: 2, // braucht 2 aktive Symbiosen (Mutationen)
    leafColor: 0x2a7a1a,
    description: 'Breite Krone. Das Netzwerk beginnt.',
  },
];

export const RESOURCES = {
  light: {
    name: 'Licht',
    emoji: '☀️',
    color: '#f0e060',
    max: 500,
    baseRate: 0.8, // pro Sekunde
  },
  water: {
    name: 'Wasser',
    emoji: '💧',
    color: '#60a0f0',
    max: 500,
    baseRate: 0.5,
  },
  nutrients: {
    name: 'Nährstoffe',
    emoji: '🌱',
    color: '#80c040',
    max: 500,
    baseRate: 0.3,
  },
};

// Mutations-Definitionen (GDD §3.3)
export const MUTATIONS = [
  {
    id: 'deep_roots',
    name: 'Tiefe Wurzeln',
    emoji: '🌿',
    type: 'passive',
    description: 'Der Baum gräbt tiefere Wurzeln. Wasser-Regeneration +40% dauerhaft.',
    lore: 'Unter der Erde träumt der Baum von Meeren, die längst verschwunden sind.',
    cost: { light: 60, water: 20, nutrients: 30 },
    requiredPhase: 0,
    exclusiveWith: [],
    effect: { waterRateBonus: 0.4 },
    visual: { trunkColorTint: 0x2a1a0a, rootExtra: 2 },
    unlocked: false,
    active: false,
  },
  {
    id: 'bioluminescence',
    name: 'Biolumineszenz',
    emoji: '✨',
    type: 'active',
    description: 'Leuchtende Blätter locken Nachtinsekten an. Nährstoffe +50%, aber Wasser -20%.',
    lore: 'In der Nacht leuchtet der Wald wie ein lebendiger Sternenhimmel.',
    cost: { light: 120, water: 50, nutrients: 40 },
    requiredPhase: 1,
    exclusiveWith: ['fire_bark'],
    effect: { nutrientsRateBonus: 0.5, waterRateBonus: -0.2 },
    visual: { leafGlow: true, leafColor: 0x40ff80 },
    unlocked: false,
    active: false,
  },
  {
    id: 'mycel_bridge',
    name: 'Myzelbücke',
    emoji: '🍄',
    type: 'symbiosis',
    description: 'Pilznetzwerk im Boden verbindet alle Ressourcen. Alle Raten +20%.',
    lore: 'Unter jedem Wald schlägt ein zweites Herz aus Pilzfäden.',
    cost: { light: 80, water: 80, nutrients: 100 },
    requiredPhase: 1,
    exclusiveWith: [],
    effect: { allRatesBonus: 0.2 },
    visual: { showMycel: true },
    unlocked: false,
    active: false,
  },
  {
    id: 'fire_bark',
    name: 'Feuerfeste Rinde',
    emoji: '🔥',
    type: 'crisis',
    description: 'Nach dem Überstehen einer Dürre wächst feuerfeste Rinde. Wasser-Verlust -30%.',
    lore: 'Was das Feuer nicht bricht, macht es unsterblich.',
    cost: { light: 0, water: 0, nutrients: 0 }, // wird durch Krise freigeschaltet
    requiredPhase: 1,
    requiredCrisis: 'drought',
    exclusiveWith: ['bioluminescence'],
    effect: { waterDrainReduction: 0.3 },
    visual: { trunkColorTint: 0x8a2010 },
    unlocked: false,
    active: false,
  },
  {
    id: 'sun_crown',
    name: 'Sonnen-Krone',
    emoji: '🌞',
    type: 'active',
    description: 'Die Krone richtet sich zur Sonne aus. Licht +60%, aber langsames Wachstum.',
    lore: 'Manche Bäume verbiegen ihr ganzes Leben, um dem Licht zu folgen.',
    cost: { light: 150, water: 30, nutrients: 60 },
    requiredPhase: 1,
    exclusiveWith: [],
    effect: { lightRateBonus: 0.6 },
    visual: { leafColor: 0xf0d020, crownTilt: true },
    unlocked: false,
    active: false,
  },
];
