// Jahreszeiten-Konfiguration – alle Werte zentral änderbar

export const SEASON_DURATION_MS = 60_000; // 60 Sekunden pro Jahreszeit

export const SEASONS = [
  {
    id: 'spring',
    name: 'Frühling',
    emoji: '🌸',
    skyTop: '#1a2e1a',
    skyBottom: '#2d5a27',
    groundColor: '#3d6b2a',
    ambientLight: '#a8d878',
    resourceMultiplier: { light: 1.2, water: 1.4, nutrients: 1.0, symbiosis: 1.3 },
    events: [
      {
        id: 'bloom',
        name: 'Blütenpracht',
        emoji: '🌸',
        chance: 0.004,
        duration: 8000,
        effect: { light: +1.5, water: -0.3, nutrients: +0.5, symbiosis: +0.8 },
        description: 'Eine Blütenpracht verstärkt die Photosynthese!',
        color: 0xffb8d0,
      },
    ],
    description: 'Schnelles Wachstum. Neue Arten wandern ein.',
  },
  {
    id: 'summer',
    name: 'Sommer',
    emoji: '☀️',
    skyTop: '#0a1a0a',
    skyBottom: '#1e4a10',
    groundColor: '#4a7a1e',
    ambientLight: '#f0e060',
    resourceMultiplier: { light: 1.5, water: 0.7, nutrients: 1.2, symbiosis: 1.6 },
    events: [
      {
        id: 'drought',
        name: 'Dürre',
        emoji: '🔥',
        chance: 0.006,
        duration: 10000,
        effect: { light: +0.5, water: -1.8, nutrients: -0.5, symbiosis: -0.3 },
        description: 'Extreme Hitze! Wasser verdunstet rapide.',
        color: 0xff6020,
      },
      {
        id: 'heatwave',
        name: 'Hitzewelle',
        emoji: '🌡️',
        chance: 0.003,
        duration: 6000,
        effect: { light: +0.3, water: -1.2, nutrients: 0, symbiosis: 0 },
        description: 'Sengend heiß – Wasser ist knapp.',
        color: 0xffa040,
      },
    ],
    description: 'Maximale Symbiose. Aber Brandgefahr.',
  },
  {
    id: 'autumn',
    name: 'Herbst',
    emoji: '🍂',
    skyTop: '#1a1005',
    skyBottom: '#3d2a10',
    groundColor: '#5a3a0a',
    ambientLight: '#e08030',
    resourceMultiplier: { light: 0.9, water: 1.1, nutrients: 1.5, symbiosis: 0.9 },
    events: [
      {
        id: 'windstorm',
        name: 'Herbststurm',
        emoji: '🌪️',
        chance: 0.005,
        duration: 7000,
        effect: { light: -0.8, water: +1.0, nutrients: -0.6, symbiosis: -0.5 },
        description: 'Ein Sturm fegt über das Land – Ressourcen schwinden!',
        color: 0xd07020,
      },
      {
        id: 'harvest',
        name: 'Erntesegen',
        emoji: '🍄',
        chance: 0.004,
        duration: 6000,
        effect: { light: 0, water: 0, nutrients: +2.5, symbiosis: +1.0 },
        description: 'Gefallene Blätter nähren den Boden.',
        color: 0x90c040,
      },
    ],
    description: 'Ressourcen sammeln für den Winter.',
  },
  {
    id: 'winter',
    name: 'Winter',
    emoji: '❄️',
    skyTop: '#050a14',
    skyBottom: '#0a1a2e',
    groundColor: '#c8d8e8',
    ambientLight: '#6090c0',
    resourceMultiplier: { light: 0.5, water: 0.6, nutrients: 0.4, symbiosis: 0.3 },
    events: [
      {
        id: 'blizzard',
        name: 'Schneesturm',
        emoji: '❄️',
        chance: 0.005,
        duration: 12000,
        effect: { light: -1.0, water: -0.8, nutrients: -1.0, symbiosis: -0.8 },
        description: 'Ein Blizzard zieht auf! Alle Ressourcen sinken.',
        color: 0xa0c8f0,
      },
      {
        id: 'frost',
        name: 'Frost',
        emoji: '🧊',
        chance: 0.007,
        duration: 8000,
        effect: { light: -0.5, water: -0.5, nutrients: -0.8, symbiosis: -0.4 },
        description: 'Tiefer Frost – Nährstoffe gefrieren im Boden.',
        color: 0x80a8ff,
      },
    ],
    description: 'Überlebensmodus. Falsche Mutationen töten Arten.',
  },
];

export const TREE_PHASES = [
  {
    id: 'seedling',
    name: 'Sämling',
    trunkHeight: 60,
    trunkWidth: 8,
    levels: 2,
    branchSpread: 40,
    growthCost: null,
    requiredSymbioses: 0,
    leafColor: 0x4a9a3a,
    description: 'Ein kleines Bäumchen. Voller Potenzial.',
  },
  {
    id: 'young',
    name: 'Junger Baum',
    trunkHeight: 120,
    trunkWidth: 14,
    levels: 3,
    branchSpread: 70,
    growthCost: { light: 80, water: 40, nutrients: 20 },
    requiredSymbioses: 0,
    leafColor: 0x3a8a2a,
    description: 'Die Krone wird sichtbar. Erste Wurzeln greifen tief.',
  },
  {
    id: 'grown',
    name: 'Ausgewachsener Baum',
    trunkHeight: 200,
    trunkWidth: 22,
    levels: 4,
    branchSpread: 110,
    growthCost: { light: 200, water: 100, nutrients: 80 },
    requiredSymbioses: 2,
    leafColor: 0x2a7a1a,
    description: 'Breite Krone. Das Netzwerk beginnt.',
  },
  {
    id: 'ancient',
    name: 'Urbaum',
    trunkHeight: 310,
    trunkWidth: 34,
    levels: 5,
    branchSpread: 160,
    growthCost: { light: 500, water: 300, nutrients: 250 },
    requiredSymbioses: 4,
    leafColor: 0x1a6010,
    description: 'Ein Jahrtausende alter Riese. Das Ökosystem zentriert sich um dich.',
  },
];

export const RESOURCES = {
  light: {
    name: 'Licht',
    emoji: '☀️',
    color: '#f0e060',
    max: 500,
    baseRate: 0.8,
  },
  water: {
    name: 'Wasser',
    emoji: '💧',
    color: '#60a0f0',
    max: 500,
    baseRate: 0.5,
  },
  nutrients: {
    name: 'Nährstoffe',
    emoji: '🌱',
    color: '#80c040',
    max: 500,
    baseRate: 0.3,
  },
  symbiosis: {
    name: 'Symbiose',
    emoji: '🪸',
    color: '#40d0a0',
    max: 500,
    baseRate: 0.15,
  },
};

export const MUTATIONS = [
  {
    id: 'deep_roots',
    name: 'Tiefe Wurzeln',
    emoji: '🌿',
    type: 'passive',
    description: 'Der Baum gräbt tiefere Wurzeln. Wasser-Regeneration +40% dauerhaft. Sichtbar als extra Wurzeln.',
    lore: 'Unter der Erde träumt der Baum von Meeren, die längst verschwunden sind.',
    cost: { light: 60, water: 20, nutrients: 30 },
    requiredPhase: 0,
    exclusiveWith: [],
    effect: { waterRateBonus: 0.4 },
    visual: { trunkColorTint: 0x2a1a0a, rootExtra: 3 },
    unlocked: false,
    active: false,
  },
  {
    id: 'bioluminescence',
    name: 'Biolumineszenz',
    emoji: '✨',
    type: 'active',
    description: 'Leuchtende Blätter locken Nachtinsekten. Nährstoffe +50%, Wasser -20%. Blätter leuchten grün.',
    lore: 'In der Nacht leuchtet der Wald wie ein lebendiger Sternenhimmel.',
    cost: { light: 120, water: 50, nutrients: 40 },
    requiredPhase: 1,
    exclusiveWith: ['fire_bark'],
    effect: { nutrientsRateBonus: 0.5, waterRateBonus: -0.2 },
    visual: { leafGlow: true, leafColor: 0x40ff80 },
    unlocked: false,
    active: false,
  },
  {
    id: 'mycel_bridge',
    name: 'Myzelgefüge',
    emoji: '🍄',
    type: 'symbiosis',
    description: 'Pilznetzwerk verbindet alle Ressourcen. Alle Raten +20%. Myzel sichtbar im Boden.',
    lore: 'Unter jedem Wald schlägt ein zweites Herz aus Pilzfäden.',
    cost: { light: 80, water: 80, nutrients: 100 },
    requiredPhase: 1,
    exclusiveWith: [],
    effect: { allRatesBonus: 0.2 },
    visual: { showMycel: true },
    unlocked: false,
    active: false,
  },
  {
    id: 'fire_bark',
    name: 'Feuerfeste Rinde',
    emoji: '🔥',
    type: 'crisis',
    description: 'Nach einer Dürre wächst feuerfeste Rinde. Wasser-Verlust -30%. Stamm wird rötlich.',
    lore: 'Was das Feuer nicht bricht, macht es unsterblich.',
    cost: { light: 0, water: 0, nutrients: 0 },
    requiredPhase: 1,
    requiredCrisis: 'drought',
    exclusiveWith: ['bioluminescence'],
    effect: { waterDrainReduction: 0.3 },
    visual: { trunkColorTint: 0x8a2010 },
    unlocked: false,
    active: false,
  },
  {
    id: 'sun_crown',
    name: 'Sonnen-Krone',
    emoji: '🌞',
    type: 'active',
    description: 'Krone richtet sich zur Sonne. Licht +60%. Blätter werden golden.',
    lore: 'Manche Bäume verbiegen ihr ganzes Leben, um dem Licht zu folgen.',
    cost: { light: 150, water: 30, nutrients: 60 },
    requiredPhase: 1,
    exclusiveWith: [],
    effect: { lightRateBonus: 0.6 },
    visual: { leafColor: 0xf0d020, crownTilt: true },
    unlocked: false,
    active: false,
  },
  {
    id: 'root_network',
    name: 'Wurzelnetz',
    emoji: '🌐',
    type: 'symbiosis',
    description: 'Weitverzweigte Wurzeln teilen Wasser mit Nachbarpflanzen. Symbiose +35%.',
    lore: 'Ein Wald ist kein Wettbewerb – er ist ein Gespräch.',
    cost: { light: 60, water: 120, nutrients: 80 },
    requiredPhase: 2,
    exclusiveWith: [],
    effect: { allRatesBonus: 0.1, waterRateBonus: 0.25 },
    visual: { rootExtra: 3 },
    unlocked: false,
    active: false,
  },
];

export const CODEX_ENTRIES = [
  { id: 'myzel',       name: 'Myzel',               icon: '🍄', cat: 'Pilznetzwerke', cond: 'Bodenfeuchte ≥ 70%',           unlocked: false },
  { id: 'glowshroom',  name: 'Geisterpilz',          icon: '🟣', cat: 'Pilznetzwerke', cond: 'Biolumineszenz aktiv',         unlocked: false },
  { id: 'fireswamp',   name: 'Feuerschwamm',         icon: '🔴', cat: 'Pilznetzwerke', cond: 'Dürre-Event überleben',        unlocked: false },
  { id: 'firefly',     name: 'Glühwürmchen',        icon: '🪲', cat: 'Tiere',         cond: 'Biolumineszenz + Sommer',      unlocked: false },
  { id: 'boar',        name: 'Wildschwein',          icon: '🐗', cat: 'Tiere',         cond: '5+ Jahre, Nährstoffe > 300',   unlocked: false },
  { id: 'moth',        name: 'Riesenmotte',          icon: '🦋', cat: 'Tiere',         cond: 'Myzelgefüge + Nacht',         unlocked: false },
  { id: 'sundew',      name: 'Sonnentau',            icon: '🌿', cat: 'Pflanzen',      cond: 'Frühling + Wasser > 350',      unlocked: false },
  { id: 'titan_arum',  name: 'Titanenwurz',          icon: '🌺', cat: 'Pflanzen',      cond: 'Jahr 10+, Symbiose > 300',     unlocked: false },
  { id: 'moonflower',  name: 'Mondblume',            icon: '🌙', cat: 'Pflanzen',      cond: 'Winter überleben + Biolum',    unlocked: false },
  { id: 'parasite',    name: 'Schmarotzerpflanze',   icon: '🦠', cat: 'Parasiten',     cond: 'Krisen-Event überleben',        unlocked: false },
  { id: 'eternal',     name: 'Ewiger Schwamm',       icon: '♾️', cat: 'Legendarys',    cond: 'Alle Pilze entdeckt',           unlocked: false },
  { id: 'worldroot',   name: 'Weltenwurzel',         icon: '🌍', cat: 'Legendarys',    cond: 'Alle Mutationen aktiv',          unlocked: false },
];
